# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.
# Version of this configuration file's structure and semantics in AzureML.
# This directive is stored in a comment to preserve the Conda file structure.
# [AzureMlVersion] = 2

name: obj_detect_training_env
channels:
  - conda-forge

dependencies:
  - python=3.8.*
  - numpy==1.16.2
  - pandas==0.23.4
  - scikit-learn>=0.19.0,<=0.20.3
  - py-xgboost==0.90
  - fbprophet==0.5
  - psutil>=5.2.2,<6.0.0
  - pip

  - pip:
      - azureml-sdk
      - azureml-defaults
      - azureml-dataprep<2.1.0a,>=2.0.1a
      - inference-schema[numpy-support]
      - azure-storage-blob
      - opencensus-ext-azure>=1.0.1
      - keras==2.4.3
      - tensorflow==2.3.1
      - joblib==0.17.0
      - py-cpuinfo==5.0.0
      - pycocotools
      - tf_lim
      - tf-models-official
